[package]
name = "thesis_vst"
version = "0.1.0"
edition = "2024"
license = "GPLv3"
description = "A VST3-based suite of DSP effects"
authors = ["Callum Jones"]

[dependencies]
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = ["assert_process_allocs"] }
