[package]
name = "benches"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
plugin-utils = { path = "../plugin-utils" }
plugin-mute = { path = "../plugin-mute" }

[[bench]]
name = "plugin_benchmarks"
harness = false

